import type { PayloadAction } from "@reduxjs/toolkit";
import { createSlice } from "@reduxjs/toolkit";

import { fetchWeekWeather } from "components/weekPageWeather/getWeekWeather/getWeeklyForecast";

interface IWeekState {
  loading: boolean;
  error: null;
  weekWeather: [] | Week;
}
const initialState: IWeekState = {
  loading: false,
  error: null,
  weekWeather: [],
};

export const weatherWeekSlice = createSlice({
  name: "WeatherWeek",
  initialState,
  reducers: {
    addWeekWeather: (state, action: PayloadAction<Week>) => {
      state.weekWeather = action.payload;
    },
  },
  extraReducers: (builder) => {
    builder
      .addCase(fetchWeekWeather.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(fetchWeekWeather.fulfilled, (state) => {
        state.loading = false;
      })
      .addCase(
        fetchWeekWeather.rejected,
        (state: { loading: boolean; error: unknown }, action) => {
          state.loading = false;
          state.error = action.payload;
        }
      );
  },
});

export const { addWeekWeather } = weatherWeekSlice.actions;

export default weatherWeekSlice.reducer;

interface Week {
  location: {
    name: "Moscow";
    region: "Moscow";
    country: "Russia";
    lat: 53.9;
    lon: 27.57;
    tz_id: "Europe/Moscow";
    localtime_epoch: 1701590070;
    localtime: "2023-12-03 10:54";
  };
  current: {
    last_updated_epoch: 1701589500;
    last_updated: "2023-12-03 10:45";
    temp_c: -5.0;
    temp_f: 23.0;
    is_day: 1;
    condition: {
      text: "Moderate snow";
      icon: "//cdn.weatherapi.com/weather/64x64/day/332.png";
      code: 1219;
    };
    wind_mph: 9.4;
    wind_kph: 15.1;
    wind_degree: 10;
    wind_dir: "N";
    pressure_mb: 1004.0;
    pressure_in: 29.65;
    precip_mm: 0.76;
    precip_in: 0.03;
    humidity: 93;
    cloud: 100;
    feelslike_c: -11.7;
    feelslike_f: 10.9;
    vis_km: 1.8;
    vis_miles: 1.0;
    uv: 1.0;
    gust_mph: 18.1;
    gust_kph: 29.1;
  };
  forecast: {
    forecastday: [
      {
        date: "2023-12-03";
        date_epoch: 1701561600;
        day: {
          maxtemp_c: -6.4;
          maxtemp_f: 20.4;
          mintemp_c: -9.9;
          mintemp_f: 14.1;
          avgtemp_c: -7.5;
          avgtemp_f: 18.5;
          maxwind_mph: 13.4;
          maxwind_kph: 21.6;
          totalprecip_mm: 8.64;
          totalprecip_in: 0.34;
          totalsnow_cm: 7.31;
          avgvis_km: 5.3;
          avgvis_miles: 3.0;
          avghumidity: 95.0;
          daily_will_it_rain: 1;
          daily_chance_of_rain: 76;
          daily_will_it_snow: 0;
          daily_chance_of_snow: 53;
          condition: {
            text: "Heavy snow";
            icon: "//cdn.weatherapi.com/weather/64x64/day/338.png";
            code: 1225;
          };
          uv: 1.0;
        };
        astro: {
          sunrise: "09:07 AM";
          sunset: "04:51 PM";
          moonrise: "10:41 PM";
          moonset: "01:53 PM";
          moon_phase: "Waning Gibbous";
          moon_illumination: 71;
          is_moon_up: 1;
          is_sun_up: 0;
        };
        hour: [
          {
            time_epoch: 1701550800;
            time: "2023-12-03 00:00";
            temp_c: -5.9;
            temp_f: 21.3;
            is_day: 0;
            condition: {
              text: "Mist";
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png";
              code: 1030;
            };
            wind_mph: 7.6;
            wind_kph: 12.2;
            wind_degree: 60;
            wind_dir: "ENE";
            pressure_mb: 1009.0;
            pressure_in: 29.8;
            precip_mm: 0.01;
            precip_in: 0.0;
            humidity: 97;
            cloud: 100;
            feelslike_c: -11.1;
            feelslike_f: 12.1;
            windchill_c: -11.1;
            windchill_f: 12.1;
            heatindex_c: -5.9;
            heatindex_f: 21.3;
            dewpoint_c: -6.4;
            dewpoint_f: 20.6;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 64;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 11.8;
            gust_kph: 19.0;
            uv: 1.0;
          },
          {
            time_epoch: 1701554400;
            time: "2023-12-03 01:00";
            temp_c: -5.9;
            temp_f: 21.4;
            is_day: 0;
            condition: {
              text: "Light freezing rain";
              icon: "//cdn.weatherapi.com/weather/64x64/night/311.png";
              code: 1198;
            };
            wind_mph: 9.4;
            wind_kph: 15.1;
            wind_degree: 58;
            wind_dir: "ENE";
            pressure_mb: 1008.0;
            pressure_in: 29.77;
            precip_mm: 0.01;
            precip_in: 0.0;
            humidity: 97;
            cloud: 100;
            feelslike_c: -11.7;
            feelslike_f: 10.9;
            windchill_c: -11.7;
            windchill_f: 10.9;
            heatindex_c: -5.9;
            heatindex_f: 21.4;
            dewpoint_c: -6.4;
            dewpoint_f: 20.6;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 70;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 14.4;
            gust_kph: 23.1;
            uv: 1.0;
          },
          {
            time_epoch: 1701558000;
            time: "2023-12-03 02:00";
            temp_c: -5.7;
            temp_f: 21.7;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 9.8;
            wind_kph: 15.8;
            wind_degree: 53;
            wind_dir: "NE";
            pressure_mb: 1007.0;
            pressure_in: 29.75;
            precip_mm: 0.07;
            precip_in: 0.0;
            humidity: 96;
            cloud: 100;
            feelslike_c: -11.7;
            feelslike_f: 11.0;
            windchill_c: -11.7;
            windchill_f: 11.0;
            heatindex_c: -5.7;
            heatindex_f: 21.7;
            dewpoint_c: -6.2;
            dewpoint_f: 20.8;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 85;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 14.4;
            gust_kph: 23.1;
            uv: 1.0;
          },
          {
            time_epoch: 1701561600;
            time: "2023-12-03 03:00";
            temp_c: -5.8;
            temp_f: 21.6;
            is_day: 0;
            condition: {
              text: "Heavy snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/338.png";
              code: 1225;
            };
            wind_mph: 10.1;
            wind_kph: 16.2;
            wind_degree: 47;
            wind_dir: "NE";
            pressure_mb: 1007.0;
            pressure_in: 29.75;
            precip_mm: 1.03;
            precip_in: 0.04;
            humidity: 96;
            cloud: 100;
            feelslike_c: -11.8;
            feelslike_f: 10.7;
            windchill_c: -11.8;
            windchill_f: 10.7;
            heatindex_c: -5.8;
            heatindex_f: 21.5;
            dewpoint_c: -6.3;
            dewpoint_f: 20.6;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 96;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 14.7;
            gust_kph: 23.7;
            uv: 1.0;
          },
          {
            time_epoch: 1701565200;
            time: "2023-12-03 04:00";
            temp_c: -6.1;
            temp_f: 21.1;
            is_day: 0;
            condition: {
              text: "Heavy snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/338.png";
              code: 1225;
            };
            wind_mph: 11.6;
            wind_kph: 18.7;
            wind_degree: 46;
            wind_dir: "NE";
            pressure_mb: 1006.0;
            pressure_in: 29.72;
            precip_mm: 0.89;
            precip_in: 0.03;
            humidity: 95;
            cloud: 100;
            feelslike_c: -12.7;
            feelslike_f: 9.2;
            windchill_c: -12.7;
            windchill_f: 9.2;
            heatindex_c: -6.1;
            heatindex_f: 21.1;
            dewpoint_c: -6.7;
            dewpoint_f: 20.0;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 97;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 17.0;
            gust_kph: 27.3;
            uv: 1.0;
          },
          {
            time_epoch: 1701568800;
            time: "2023-12-03 05:00";
            temp_c: -6.3;
            temp_f: 20.7;
            is_day: 0;
            condition: {
              text: "Heavy snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/338.png";
              code: 1225;
            };
            wind_mph: 12.1;
            wind_kph: 19.4;
            wind_degree: 32;
            wind_dir: "NNE";
            pressure_mb: 1006.0;
            pressure_in: 29.7;
            precip_mm: 1.24;
            precip_in: 0.05;
            humidity: 95;
            cloud: 100;
            feelslike_c: -13.1;
            feelslike_f: 8.4;
            windchill_c: -13.1;
            windchill_f: 8.4;
            heatindex_c: -6.3;
            heatindex_f: 20.7;
            dewpoint_c: -6.9;
            dewpoint_f: 19.5;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 97;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 17.6;
            gust_kph: 28.3;
            uv: 1.0;
          },
          {
            time_epoch: 1701572400;
            time: "2023-12-03 06:00";
            temp_c: -6.4;
            temp_f: 20.4;
            is_day: 0;
            condition: {
              text: "Heavy snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/338.png";
              code: 1225;
            };
            wind_mph: 11.4;
            wind_kph: 18.4;
            wind_degree: 17;
            wind_dir: "NNE";
            pressure_mb: 1006.0;
            pressure_in: 29.7;
            precip_mm: 1.68;
            precip_in: 0.07;
            humidity: 96;
            cloud: 100;
            feelslike_c: -13.1;
            feelslike_f: 8.5;
            windchill_c: -13.1;
            windchill_f: 8.5;
            heatindex_c: -6.5;
            heatindex_f: 20.4;
            dewpoint_c: -7.0;
            dewpoint_f: 19.3;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 97;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 16.4;
            gust_kph: 26.5;
            uv: 1.0;
          },
          {
            time_epoch: 1701576000;
            time: "2023-12-03 07:00";
            temp_c: -6.7;
            temp_f: 20.0;
            is_day: 0;
            condition: {
              text: "Heavy snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/338.png";
              code: 1225;
            };
            wind_mph: 12.3;
            wind_kph: 19.8;
            wind_degree: 13;
            wind_dir: "NNE";
            pressure_mb: 1006.0;
            pressure_in: 29.7;
            precip_mm: 1.28;
            precip_in: 0.05;
            humidity: 95;
            cloud: 100;
            feelslike_c: -13.6;
            feelslike_f: 7.5;
            windchill_c: -13.6;
            windchill_f: 7.5;
            heatindex_c: -6.7;
            heatindex_f: 20.0;
            dewpoint_c: -7.3;
            dewpoint_f: 18.9;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 96;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 17.8;
            gust_kph: 28.6;
            uv: 1.0;
          },
          {
            time_epoch: 1701579600;
            time: "2023-12-03 08:00";
            temp_c: -6.9;
            temp_f: 19.6;
            is_day: 0;
            condition: {
              text: "Heavy snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/338.png";
              code: 1225;
            };
            wind_mph: 13.2;
            wind_kph: 21.2;
            wind_degree: 13;
            wind_dir: "NNE";
            pressure_mb: 1006.0;
            pressure_in: 29.7;
            precip_mm: 0.66;
            precip_in: 0.03;
            humidity: 94;
            cloud: 100;
            feelslike_c: -14.2;
            feelslike_f: 6.5;
            windchill_c: -14.2;
            windchill_f: 6.5;
            heatindex_c: -6.9;
            heatindex_f: 19.6;
            dewpoint_c: -7.6;
            dewpoint_f: 18.3;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 96;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 19.2;
            gust_kph: 31.0;
            uv: 1.0;
          },
          {
            time_epoch: 1701583200;
            time: "2023-12-03 09:00";
            temp_c: -7.0;
            temp_f: 19.4;
            is_day: 0;
            condition: {
              text: "Heavy snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/338.png";
              code: 1225;
            };
            wind_mph: 11.9;
            wind_kph: 19.1;
            wind_degree: 1;
            wind_dir: "N";
            pressure_mb: 1007.0;
            pressure_in: 29.72;
            precip_mm: 0.65;
            precip_in: 0.03;
            humidity: 95;
            cloud: 100;
            feelslike_c: -13.9;
            feelslike_f: 7.0;
            windchill_c: -13.9;
            windchill_f: 7.0;
            heatindex_c: -7.0;
            heatindex_f: 19.4;
            dewpoint_c: -7.7;
            dewpoint_f: 18.2;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 96;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 16.9;
            gust_kph: 27.2;
            uv: 1.0;
          },
          {
            time_epoch: 1701586800;
            time: "2023-12-03 10:00";
            temp_c: -5.0;
            temp_f: 23.0;
            is_day: 1;
            condition: {
              text: "Moderate snow";
              icon: "//cdn.weatherapi.com/weather/64x64/day/332.png";
              code: 1219;
            };
            wind_mph: 9.4;
            wind_kph: 15.1;
            wind_degree: 10;
            wind_dir: "N";
            pressure_mb: 1004.0;
            pressure_in: 29.65;
            precip_mm: 0.76;
            precip_in: 0.03;
            humidity: 93;
            cloud: 100;
            feelslike_c: -14.3;
            feelslike_f: 6.2;
            windchill_c: -14.3;
            windchill_f: 6.2;
            heatindex_c: -7.1;
            heatindex_f: 19.3;
            dewpoint_c: -7.8;
            dewpoint_f: 18.0;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 95;
            vis_km: 1.8;
            vis_miles: 1.0;
            gust_mph: 18.1;
            gust_kph: 29.1;
            uv: 1.0;
          },
          {
            time_epoch: 1701590400;
            time: "2023-12-03 11:00";
            temp_c: -7.0;
            temp_f: 19.4;
            is_day: 1;
            condition: {
              text: "Moderate snow";
              icon: "//cdn.weatherapi.com/weather/64x64/day/332.png";
              code: 1219;
            };
            wind_mph: 12.5;
            wind_kph: 20.2;
            wind_degree: 346;
            wind_dir: "NNW";
            pressure_mb: 1008.0;
            pressure_in: 29.78;
            precip_mm: 0.21;
            precip_in: 0.01;
            humidity: 94;
            cloud: 100;
            feelslike_c: -14.1;
            feelslike_f: 6.6;
            windchill_c: -14.1;
            windchill_f: 6.6;
            heatindex_c: -7.0;
            heatindex_f: 19.4;
            dewpoint_c: -7.8;
            dewpoint_f: 18.0;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 95;
            vis_km: 5.0;
            vis_miles: 3.0;
            gust_mph: 17.2;
            gust_kph: 27.8;
            uv: 1.0;
          },
          {
            time_epoch: 1701594000;
            time: "2023-12-03 12:00";
            temp_c: -6.9;
            temp_f: 19.7;
            is_day: 1;
            condition: {
              text: "Moderate snow";
              icon: "//cdn.weatherapi.com/weather/64x64/day/332.png";
              code: 1219;
            };
            wind_mph: 13.0;
            wind_kph: 20.9;
            wind_degree: 342;
            wind_dir: "NNW";
            pressure_mb: 1009.0;
            pressure_in: 29.78;
            precip_mm: 0.13;
            precip_in: 0.01;
            humidity: 94;
            cloud: 100;
            feelslike_c: -14.1;
            feelslike_f: 6.7;
            windchill_c: -14.1;
            windchill_f: 6.7;
            heatindex_c: -6.9;
            heatindex_f: 19.7;
            dewpoint_c: -7.7;
            dewpoint_f: 18.2;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 95;
            vis_km: 5.0;
            vis_miles: 3.0;
            gust_mph: 17.7;
            gust_kph: 28.4;
            uv: 1.0;
          },
          {
            time_epoch: 1701597600;
            time: "2023-12-03 13:00";
            temp_c: -6.8;
            temp_f: 19.8;
            is_day: 1;
            condition: {
              text: "Light freezing rain";
              icon: "//cdn.weatherapi.com/weather/64x64/day/311.png";
              code: 1198;
            };
            wind_mph: 13.4;
            wind_kph: 21.6;
            wind_degree: 339;
            wind_dir: "NNW";
            pressure_mb: 1009.0;
            pressure_in: 29.8;
            precip_mm: 0.01;
            precip_in: 0.0;
            humidity: 92;
            cloud: 100;
            feelslike_c: -14.1;
            feelslike_f: 6.6;
            windchill_c: -14.1;
            windchill_f: 6.6;
            heatindex_c: -6.8;
            heatindex_f: 19.8;
            dewpoint_c: -7.8;
            dewpoint_f: 17.9;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 87;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 18.3;
            gust_kph: 29.4;
            uv: 1.0;
          },
          {
            time_epoch: 1701601200;
            time: "2023-12-03 14:00";
            temp_c: -7.1;
            temp_f: 19.2;
            is_day: 1;
            condition: {
              text: "Overcast";
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png";
              code: 1009;
            };
            wind_mph: 12.1;
            wind_kph: 19.4;
            wind_degree: 321;
            wind_dir: "NW";
            pressure_mb: 1010.0;
            pressure_in: 29.84;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 92;
            cloud: 100;
            feelslike_c: -14.1;
            feelslike_f: 6.6;
            windchill_c: -14.1;
            windchill_f: 6.6;
            heatindex_c: -7.1;
            heatindex_f: 19.2;
            dewpoint_c: -8.2;
            dewpoint_f: 17.3;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 17.1;
            gust_kph: 27.5;
            uv: 1.0;
          },
          {
            time_epoch: 1701604800;
            time: "2023-12-03 15:00";
            temp_c: -7.3;
            temp_f: 18.8;
            is_day: 1;
            condition: {
              text: "Cloudy";
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png";
              code: 1006;
            };
            wind_mph: 11.9;
            wind_kph: 19.1;
            wind_degree: 327;
            wind_dir: "NNW";
            pressure_mb: 1011.0;
            pressure_in: 29.86;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 92;
            cloud: 67;
            feelslike_c: -14.3;
            feelslike_f: 6.3;
            windchill_c: -14.3;
            windchill_f: 6.3;
            heatindex_c: -7.3;
            heatindex_f: 18.8;
            dewpoint_c: -8.4;
            dewpoint_f: 16.9;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 17.2;
            gust_kph: 27.8;
            uv: 1.0;
          },
          {
            time_epoch: 1701608400;
            time: "2023-12-03 16:00";
            temp_c: -8.3;
            temp_f: 17.1;
            is_day: 1;
            condition: {
              text: "Overcast";
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png";
              code: 1009;
            };
            wind_mph: 10.3;
            wind_kph: 16.6;
            wind_degree: 319;
            wind_dir: "NW";
            pressure_mb: 1012.0;
            pressure_in: 29.89;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 91;
            cloud: 100;
            feelslike_c: -15.0;
            feelslike_f: 5.0;
            windchill_c: -15.0;
            windchill_f: 5.0;
            heatindex_c: -8.3;
            heatindex_f: 17.1;
            dewpoint_c: -9.4;
            dewpoint_f: 15.0;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 17.0;
            gust_kph: 27.3;
            uv: 1.0;
          },
          {
            time_epoch: 1701612000;
            time: "2023-12-03 17:00";
            temp_c: -9.1;
            temp_f: 15.6;
            is_day: 0;
            condition: {
              text: "Overcast";
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png";
              code: 1009;
            };
            wind_mph: 8.5;
            wind_kph: 13.7;
            wind_degree: 302;
            wind_dir: "WNW";
            pressure_mb: 1013.0;
            pressure_in: 29.92;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 93;
            cloud: 100;
            feelslike_c: -15.3;
            feelslike_f: 4.5;
            windchill_c: -15.3;
            windchill_f: 4.5;
            heatindex_c: -9.1;
            heatindex_f: 15.7;
            dewpoint_c: -10.0;
            dewpoint_f: 13.9;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 15.3;
            gust_kph: 24.7;
            uv: 1.0;
          },
          {
            time_epoch: 1701615600;
            time: "2023-12-03 18:00";
            temp_c: -9.7;
            temp_f: 14.6;
            is_day: 0;
            condition: {
              text: "Overcast";
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png";
              code: 1009;
            };
            wind_mph: 7.8;
            wind_kph: 12.6;
            wind_degree: 289;
            wind_dir: "WNW";
            pressure_mb: 1014.0;
            pressure_in: 29.94;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 94;
            cloud: 100;
            feelslike_c: -15.7;
            feelslike_f: 3.8;
            windchill_c: -15.7;
            windchill_f: 3.8;
            heatindex_c: -9.7;
            heatindex_f: 14.6;
            dewpoint_c: -10.4;
            dewpoint_f: 13.3;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 15.1;
            gust_kph: 24.4;
            uv: 1.0;
          },
          {
            time_epoch: 1701619200;
            time: "2023-12-03 19:00";
            temp_c: -9.7;
            temp_f: 14.5;
            is_day: 0;
            condition: {
              text: "Partly cloudy";
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png";
              code: 1003;
            };
            wind_mph: 7.8;
            wind_kph: 12.6;
            wind_degree: 297;
            wind_dir: "WNW";
            pressure_mb: 1014.0;
            pressure_in: 29.95;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 94;
            cloud: 55;
            feelslike_c: -15.7;
            feelslike_f: 3.7;
            windchill_c: -15.7;
            windchill_f: 3.7;
            heatindex_c: -9.7;
            heatindex_f: 14.5;
            dewpoint_c: -10.4;
            dewpoint_f: 13.2;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 15.5;
            gust_kph: 24.9;
            uv: 1.0;
          },
          {
            time_epoch: 1701622800;
            time: "2023-12-03 20:00";
            temp_c: -9.6;
            temp_f: 14.7;
            is_day: 0;
            condition: {
              text: "Mist";
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png";
              code: 1030;
            };
            wind_mph: 7.4;
            wind_kph: 11.9;
            wind_degree: 289;
            wind_dir: "WNW";
            pressure_mb: 1015.0;
            pressure_in: 29.97;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 95;
            cloud: 74;
            feelslike_c: -15.4;
            feelslike_f: 4.3;
            windchill_c: -15.4;
            windchill_f: 4.3;
            heatindex_c: -9.6;
            heatindex_f: 14.7;
            dewpoint_c: -10.2;
            dewpoint_f: 13.6;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 14.4;
            gust_kph: 23.1;
            uv: 1.0;
          },
          {
            time_epoch: 1701626400;
            time: "2023-12-03 21:00";
            temp_c: -9.6;
            temp_f: 14.8;
            is_day: 0;
            condition: {
              text: "Mist";
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png";
              code: 1030;
            };
            wind_mph: 7.2;
            wind_kph: 11.5;
            wind_degree: 283;
            wind_dir: "WNW";
            pressure_mb: 1015.0;
            pressure_in: 29.98;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 95;
            cloud: 88;
            feelslike_c: -15.3;
            feelslike_f: 4.5;
            windchill_c: -15.3;
            windchill_f: 4.5;
            heatindex_c: -9.6;
            heatindex_f: 14.8;
            dewpoint_c: -10.2;
            dewpoint_f: 13.7;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 13.7;
            gust_kph: 22.0;
            uv: 1.0;
          },
          {
            time_epoch: 1701630000;
            time: "2023-12-03 22:00";
            temp_c: -9.7;
            temp_f: 14.5;
            is_day: 0;
            condition: {
              text: "Mist";
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png";
              code: 1030;
            };
            wind_mph: 6.9;
            wind_kph: 11.2;
            wind_degree: 285;
            wind_dir: "WNW";
            pressure_mb: 1016.0;
            pressure_in: 29.99;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 95;
            cloud: 84;
            feelslike_c: -15.3;
            feelslike_f: 4.5;
            windchill_c: -15.3;
            windchill_f: 4.5;
            heatindex_c: -9.7;
            heatindex_f: 14.5;
            dewpoint_c: -10.3;
            dewpoint_f: 13.5;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 13.5;
            gust_kph: 21.7;
            uv: 1.0;
          },
          {
            time_epoch: 1701633600;
            time: "2023-12-03 23:00";
            temp_c: -9.9;
            temp_f: 14.1;
            is_day: 0;
            condition: {
              text: "Mist";
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png";
              code: 1030;
            };
            wind_mph: 6.9;
            wind_kph: 11.2;
            wind_degree: 278;
            wind_dir: "W";
            pressure_mb: 1016.0;
            pressure_in: 30.0;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 96;
            cloud: 76;
            feelslike_c: -15.6;
            feelslike_f: 4.0;
            windchill_c: -15.6;
            windchill_f: 4.0;
            heatindex_c: -9.9;
            heatindex_f: 14.1;
            dewpoint_c: -10.5;
            dewpoint_f: 13.2;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 13.8;
            gust_kph: 22.3;
            uv: 1.0;
          },
        ];
      },
      {
        date: "2023-12-04";
        date_epoch: 1701648000;
        day: {
          maxtemp_c: -3.8;
          maxtemp_f: 25.2;
          mintemp_c: -13.3;
          mintemp_f: 8.1;
          avgtemp_c: -6.2;
          avgtemp_f: 20.8;
          maxwind_mph: 13.2;
          maxwind_kph: 21.2;
          totalprecip_mm: 0.53;
          totalprecip_in: 0.02;
          totalsnow_cm: 0.4;
          avgvis_km: 8.4;
          avgvis_miles: 5.0;
          avghumidity: 95.0;
          daily_will_it_rain: 1;
          daily_chance_of_rain: 77;
          daily_will_it_snow: 0;
          daily_chance_of_snow: 66;
          condition: {
            text: "Light snow";
            icon: "//cdn.weatherapi.com/weather/64x64/day/326.png";
            code: 1213;
          };
          uv: 1.0;
        };
        astro: {
          sunrise: "09:09 AM";
          sunset: "04:51 PM";
          moonrise: "11:57 PM";
          moonset: "02:04 PM";
          moon_phase: "Waning Gibbous";
          moon_illumination: 62;
          is_moon_up: 1;
          is_sun_up: 0;
        };
        hour: [
          {
            time_epoch: 1701637200;
            time: "2023-12-04 00:00";
            temp_c: -10.7;
            temp_f: 12.7;
            is_day: 0;
            condition: {
              text: "Mist";
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png";
              code: 1030;
            };
            wind_mph: 6.3;
            wind_kph: 10.1;
            wind_degree: 270;
            wind_dir: "W";
            pressure_mb: 1016.0;
            pressure_in: 30.02;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 96;
            cloud: 64;
            feelslike_c: -16.1;
            feelslike_f: 2.9;
            windchill_c: -16.1;
            windchill_f: 2.9;
            heatindex_c: -10.7;
            heatindex_f: 12.7;
            dewpoint_c: -11.2;
            dewpoint_f: 11.8;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 13.2;
            gust_kph: 21.2;
            uv: 1.0;
          },
          {
            time_epoch: 1701640800;
            time: "2023-12-04 01:00";
            temp_c: -11.8;
            temp_f: 10.7;
            is_day: 0;
            condition: {
              text: "Freezing fog";
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png";
              code: 1147;
            };
            wind_mph: 5.4;
            wind_kph: 8.6;
            wind_degree: 261;
            wind_dir: "W";
            pressure_mb: 1017.0;
            pressure_in: 30.02;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 97;
            cloud: 62;
            feelslike_c: -16.9;
            feelslike_f: 1.5;
            windchill_c: -16.9;
            windchill_f: 1.5;
            heatindex_c: -11.8;
            heatindex_f: 10.7;
            dewpoint_c: -12.2;
            dewpoint_f: 10.1;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 0.0;
            vis_miles: 0.0;
            gust_mph: 11.3;
            gust_kph: 18.1;
            uv: 1.0;
          },
          {
            time_epoch: 1701644400;
            time: "2023-12-04 02:00";
            temp_c: -13.3;
            temp_f: 8.1;
            is_day: 0;
            condition: {
              text: "Freezing fog";
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png";
              code: 1147;
            };
            wind_mph: 5.4;
            wind_kph: 8.6;
            wind_degree: 247;
            wind_dir: "WSW";
            pressure_mb: 1017.0;
            pressure_in: 30.03;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 99;
            cloud: 63;
            feelslike_c: -18.6;
            feelslike_f: -1.5;
            windchill_c: -18.6;
            windchill_f: -1.5;
            heatindex_c: -13.3;
            heatindex_f: 8.1;
            dewpoint_c: -13.4;
            dewpoint_f: 7.8;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 0.0;
            vis_miles: 0.0;
            gust_mph: 11.3;
            gust_kph: 18.1;
            uv: 1.0;
          },
          {
            time_epoch: 1701648000;
            time: "2023-12-04 03:00";
            temp_c: -12.3;
            temp_f: 9.8;
            is_day: 0;
            condition: {
              text: "Freezing fog";
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png";
              code: 1147;
            };
            wind_mph: 6.3;
            wind_kph: 10.1;
            wind_degree: 237;
            wind_dir: "WSW";
            pressure_mb: 1017.0;
            pressure_in: 30.03;
            precip_mm: 0.01;
            precip_in: 0.0;
            humidity: 99;
            cloud: 72;
            feelslike_c: -18.1;
            feelslike_f: -0.5;
            windchill_c: -18.1;
            windchill_f: -0.5;
            heatindex_c: -12.3;
            heatindex_f: 9.8;
            dewpoint_c: -12.5;
            dewpoint_f: 9.6;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 75;
            vis_km: 0.0;
            vis_miles: 0.0;
            gust_mph: 13.2;
            gust_kph: 21.2;
            uv: 1.0;
          },
          {
            time_epoch: 1701651600;
            time: "2023-12-04 04:00";
            temp_c: -10.1;
            temp_f: 13.7;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 6.9;
            wind_kph: 11.2;
            wind_degree: 230;
            wind_dir: "SW";
            pressure_mb: 1016.0;
            pressure_in: 30.02;
            precip_mm: 0.04;
            precip_in: 0.0;
            humidity: 97;
            cloud: 100;
            feelslike_c: -15.8;
            feelslike_f: 3.5;
            windchill_c: -15.8;
            windchill_f: 3.5;
            heatindex_c: -10.2;
            heatindex_f: 13.7;
            dewpoint_c: -10.6;
            dewpoint_f: 13.0;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 84;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 14.6;
            gust_kph: 23.4;
            uv: 1.0;
          },
          {
            time_epoch: 1701655200;
            time: "2023-12-04 05:00";
            temp_c: -7.7;
            temp_f: 18.2;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 8.7;
            wind_kph: 14.0;
            wind_degree: 236;
            wind_dir: "WSW";
            pressure_mb: 1016.0;
            pressure_in: 30.01;
            precip_mm: 0.05;
            precip_in: 0.0;
            humidity: 96;
            cloud: 97;
            feelslike_c: -13.6;
            feelslike_f: 7.5;
            windchill_c: -13.6;
            windchill_f: 7.5;
            heatindex_c: -7.7;
            heatindex_f: 18.2;
            dewpoint_c: -8.2;
            dewpoint_f: 17.2;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 82;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 16.5;
            gust_kph: 26.6;
            uv: 1.0;
          },
          {
            time_epoch: 1701658800;
            time: "2023-12-04 06:00";
            temp_c: -6.1;
            temp_f: 21.0;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 10.5;
            wind_kph: 16.9;
            wind_degree: 239;
            wind_dir: "WSW";
            pressure_mb: 1016.0;
            pressure_in: 30.0;
            precip_mm: 0.03;
            precip_in: 0.0;
            humidity: 95;
            cloud: 100;
            feelslike_c: -12.4;
            feelslike_f: 9.8;
            windchill_c: -12.4;
            windchill_f: 9.8;
            heatindex_c: -6.1;
            heatindex_f: 21.0;
            dewpoint_c: -6.8;
            dewpoint_f: 19.7;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 79;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 18.0;
            gust_kph: 28.9;
            uv: 1.0;
          },
          {
            time_epoch: 1701662400;
            time: "2023-12-04 07:00";
            temp_c: -5.1;
            temp_f: 22.8;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 11.9;
            wind_kph: 19.1;
            wind_degree: 244;
            wind_dir: "WSW";
            pressure_mb: 1016.0;
            pressure_in: 30.01;
            precip_mm: 0.04;
            precip_in: 0.0;
            humidity: 94;
            cloud: 100;
            feelslike_c: -11.5;
            feelslike_f: 11.3;
            windchill_c: -11.5;
            windchill_f: 11.3;
            heatindex_c: -5.1;
            heatindex_f: 22.8;
            dewpoint_c: -5.9;
            dewpoint_f: 21.3;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 69;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 19.2;
            gust_kph: 30.9;
            uv: 1.0;
          },
          {
            time_epoch: 1701666000;
            time: "2023-12-04 08:00";
            temp_c: -5.4;
            temp_f: 22.3;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 11.9;
            wind_kph: 19.1;
            wind_degree: 243;
            wind_dir: "WSW";
            pressure_mb: 1017.0;
            pressure_in: 30.02;
            precip_mm: 0.02;
            precip_in: 0.0;
            humidity: 94;
            cloud: 100;
            feelslike_c: -11.9;
            feelslike_f: 10.6;
            windchill_c: -11.9;
            windchill_f: 10.6;
            heatindex_c: -5.4;
            heatindex_f: 22.2;
            dewpoint_c: -6.3;
            dewpoint_f: 20.7;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 69;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 18.8;
            gust_kph: 30.2;
            uv: 1.0;
          },
          {
            time_epoch: 1701669600;
            time: "2023-12-04 09:00";
            temp_c: -5.6;
            temp_f: 21.9;
            is_day: 0;
            condition: {
              text: "Light freezing rain";
              icon: "//cdn.weatherapi.com/weather/64x64/night/311.png";
              code: 1198;
            };
            wind_mph: 11.2;
            wind_kph: 18.0;
            wind_degree: 240;
            wind_dir: "WSW";
            pressure_mb: 1017.0;
            pressure_in: 30.04;
            precip_mm: 0.01;
            precip_in: 0.0;
            humidity: 94;
            cloud: 100;
            feelslike_c: -12.0;
            feelslike_f: 10.5;
            windchill_c: -12.0;
            windchill_f: 10.5;
            heatindex_c: -5.6;
            heatindex_f: 21.9;
            dewpoint_c: -6.4;
            dewpoint_f: 20.4;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 66;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 17.4;
            gust_kph: 27.9;
            uv: 1.0;
          },
          {
            time_epoch: 1701673200;
            time: "2023-12-04 10:00";
            temp_c: -5.4;
            temp_f: 22.2;
            is_day: 1;
            condition: {
              text: "Light freezing rain";
              icon: "//cdn.weatherapi.com/weather/64x64/day/311.png";
              code: 1198;
            };
            wind_mph: 11.4;
            wind_kph: 18.4;
            wind_degree: 241;
            wind_dir: "WSW";
            pressure_mb: 1017.0;
            pressure_in: 30.04;
            precip_mm: 0.01;
            precip_in: 0.0;
            humidity: 94;
            cloud: 100;
            feelslike_c: -11.8;
            feelslike_f: 10.7;
            windchill_c: -11.8;
            windchill_f: 10.7;
            heatindex_c: -5.5;
            heatindex_f: 22.2;
            dewpoint_c: -6.2;
            dewpoint_f: 20.8;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 84;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 17.2;
            gust_kph: 27.8;
            uv: 1.0;
          },
          {
            time_epoch: 1701676800;
            time: "2023-12-04 11:00";
            temp_c: -4.5;
            temp_f: 23.8;
            is_day: 1;
            condition: {
              text: "Light freezing rain";
              icon: "//cdn.weatherapi.com/weather/64x64/day/311.png";
              code: 1198;
            };
            wind_mph: 12.1;
            wind_kph: 19.4;
            wind_degree: 245;
            wind_dir: "WSW";
            pressure_mb: 1017.0;
            pressure_in: 30.05;
            precip_mm: 0.01;
            precip_in: 0.0;
            humidity: 93;
            cloud: 100;
            feelslike_c: -10.9;
            feelslike_f: 12.4;
            windchill_c: -10.9;
            windchill_f: 12.4;
            heatindex_c: -4.5;
            heatindex_f: 23.8;
            dewpoint_c: -5.5;
            dewpoint_f: 22.1;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 88;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 17.2;
            gust_kph: 27.7;
            uv: 1.0;
          },
          {
            time_epoch: 1701680400;
            time: "2023-12-04 12:00";
            temp_c: -4.3;
            temp_f: 24.2;
            is_day: 1;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/day/326.png";
              code: 1213;
            };
            wind_mph: 13.2;
            wind_kph: 21.2;
            wind_degree: 251;
            wind_dir: "WSW";
            pressure_mb: 1017.0;
            pressure_in: 30.04;
            precip_mm: 0.02;
            precip_in: 0.0;
            humidity: 92;
            cloud: 100;
            feelslike_c: -10.9;
            feelslike_f: 12.4;
            windchill_c: -10.9;
            windchill_f: 12.4;
            heatindex_c: -4.3;
            heatindex_f: 24.2;
            dewpoint_c: -5.4;
            dewpoint_f: 22.2;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 68;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 18.5;
            gust_kph: 29.8;
            uv: 1.0;
          },
          {
            time_epoch: 1701684000;
            time: "2023-12-04 13:00";
            temp_c: -4.0;
            temp_f: 24.9;
            is_day: 1;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/day/326.png";
              code: 1213;
            };
            wind_mph: 12.8;
            wind_kph: 20.5;
            wind_degree: 252;
            wind_dir: "WSW";
            pressure_mb: 1018.0;
            pressure_in: 30.05;
            precip_mm: 0.02;
            precip_in: 0.0;
            humidity: 92;
            cloud: 100;
            feelslike_c: -10.3;
            feelslike_f: 13.4;
            windchill_c: -10.3;
            windchill_f: 13.4;
            heatindex_c: -4.0;
            heatindex_f: 24.9;
            dewpoint_c: -5.1;
            dewpoint_f: 22.8;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 66;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 17.6;
            gust_kph: 28.4;
            uv: 1.0;
          },
          {
            time_epoch: 1701687600;
            time: "2023-12-04 14:00";
            temp_c: -3.8;
            temp_f: 25.2;
            is_day: 1;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/day/326.png";
              code: 1213;
            };
            wind_mph: 12.5;
            wind_kph: 20.2;
            wind_degree: 253;
            wind_dir: "WSW";
            pressure_mb: 1018.0;
            pressure_in: 30.05;
            precip_mm: 0.03;
            precip_in: 0.0;
            humidity: 92;
            cloud: 100;
            feelslike_c: -10.1;
            feelslike_f: 13.9;
            windchill_c: -10.1;
            windchill_f: 13.9;
            heatindex_c: -3.8;
            heatindex_f: 25.2;
            dewpoint_c: -5.0;
            dewpoint_f: 23.1;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 88;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 17.5;
            gust_kph: 28.2;
            uv: 1.0;
          },
          {
            time_epoch: 1701691200;
            time: "2023-12-04 15:00";
            temp_c: -4.0;
            temp_f: 24.9;
            is_day: 1;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/day/326.png";
              code: 1213;
            };
            wind_mph: 11.4;
            wind_kph: 18.4;
            wind_degree: 252;
            wind_dir: "WSW";
            pressure_mb: 1018.0;
            pressure_in: 30.06;
            precip_mm: 0.04;
            precip_in: 0.0;
            humidity: 93;
            cloud: 100;
            feelslike_c: -10.0;
            feelslike_f: 14.1;
            windchill_c: -10.0;
            windchill_f: 14.1;
            heatindex_c: -4.0;
            heatindex_f: 24.9;
            dewpoint_c: -4.9;
            dewpoint_f: 23.2;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 67;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 16.5;
            gust_kph: 26.6;
            uv: 1.0;
          },
          {
            time_epoch: 1701694800;
            time: "2023-12-04 16:00";
            temp_c: -4.0;
            temp_f: 24.7;
            is_day: 1;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/day/326.png";
              code: 1213;
            };
            wind_mph: 11.0;
            wind_kph: 17.6;
            wind_degree: 252;
            wind_dir: "WSW";
            pressure_mb: 1018.0;
            pressure_in: 30.07;
            precip_mm: 0.04;
            precip_in: 0.0;
            humidity: 93;
            cloud: 100;
            feelslike_c: -9.9;
            feelslike_f: 14.1;
            windchill_c: -9.9;
            windchill_f: 14.1;
            heatindex_c: -4.1;
            heatindex_f: 24.7;
            dewpoint_c: -5.0;
            dewpoint_f: 23.0;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 61;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 16.7;
            gust_kph: 26.9;
            uv: 1.0;
          },
          {
            time_epoch: 1701698400;
            time: "2023-12-04 17:00";
            temp_c: -4.1;
            temp_f: 24.6;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 10.1;
            wind_kph: 16.2;
            wind_degree: 253;
            wind_dir: "WSW";
            pressure_mb: 1018.0;
            pressure_in: 30.07;
            precip_mm: 0.02;
            precip_in: 0.0;
            humidity: 93;
            cloud: 100;
            feelslike_c: -9.7;
            feelslike_f: 14.5;
            windchill_c: -9.7;
            windchill_f: 14.5;
            heatindex_c: -4.1;
            heatindex_f: 24.6;
            dewpoint_c: -5.0;
            dewpoint_f: 23.0;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 61;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 15.7;
            gust_kph: 25.3;
            uv: 1.0;
          },
          {
            time_epoch: 1701702000;
            time: "2023-12-04 18:00";
            temp_c: -4.1;
            temp_f: 24.6;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 9.8;
            wind_kph: 15.8;
            wind_degree: 251;
            wind_dir: "WSW";
            pressure_mb: 1018.0;
            pressure_in: 30.08;
            precip_mm: 0.02;
            precip_in: 0.0;
            humidity: 94;
            cloud: 100;
            feelslike_c: -9.7;
            feelslike_f: 14.6;
            windchill_c: -9.7;
            windchill_f: 14.6;
            heatindex_c: -4.1;
            heatindex_f: 24.6;
            dewpoint_c: -5.0;
            dewpoint_f: 23.0;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 85;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 15.5;
            gust_kph: 25.0;
            uv: 1.0;
          },
          {
            time_epoch: 1701705600;
            time: "2023-12-04 19:00";
            temp_c: -4.2;
            temp_f: 24.4;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 9.8;
            wind_kph: 15.8;
            wind_degree: 247;
            wind_dir: "WSW";
            pressure_mb: 1019.0;
            pressure_in: 30.08;
            precip_mm: 0.03;
            precip_in: 0.0;
            humidity: 94;
            cloud: 100;
            feelslike_c: -9.8;
            feelslike_f: 14.4;
            windchill_c: -9.8;
            windchill_f: 14.4;
            heatindex_c: -4.2;
            heatindex_f: 24.4;
            dewpoint_c: -5.0;
            dewpoint_f: 23.0;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 89;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 15.4;
            gust_kph: 24.8;
            uv: 1.0;
          },
          {
            time_epoch: 1701709200;
            time: "2023-12-04 20:00";
            temp_c: -4.2;
            temp_f: 24.5;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 9.6;
            wind_kph: 15.5;
            wind_degree: 249;
            wind_dir: "WSW";
            pressure_mb: 1019.0;
            pressure_in: 30.09;
            precip_mm: 0.03;
            precip_in: 0.0;
            humidity: 94;
            cloud: 100;
            feelslike_c: -9.7;
            feelslike_f: 14.6;
            windchill_c: -9.7;
            windchill_f: 14.6;
            heatindex_c: -4.2;
            heatindex_f: 24.5;
            dewpoint_c: -4.9;
            dewpoint_f: 23.1;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 72;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 14.7;
            gust_kph: 23.6;
            uv: 1.0;
          },
          {
            time_epoch: 1701712800;
            time: "2023-12-04 21:00";
            temp_c: -4.3;
            temp_f: 24.2;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 9.4;
            wind_kph: 15.1;
            wind_degree: 250;
            wind_dir: "WSW";
            pressure_mb: 1019.0;
            pressure_in: 30.1;
            precip_mm: 0.02;
            precip_in: 0.0;
            humidity: 95;
            cloud: 100;
            feelslike_c: -9.8;
            feelslike_f: 14.4;
            windchill_c: -9.8;
            windchill_f: 14.4;
            heatindex_c: -4.3;
            heatindex_f: 24.2;
            dewpoint_c: -5.0;
            dewpoint_f: 22.9;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 70;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 14.1;
            gust_kph: 22.6;
            uv: 1.0;
          },
          {
            time_epoch: 1701716400;
            time: "2023-12-04 22:00";
            temp_c: -4.8;
            temp_f: 23.4;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 9.4;
            wind_kph: 15.1;
            wind_degree: 246;
            wind_dir: "WSW";
            pressure_mb: 1020.0;
            pressure_in: 30.12;
            precip_mm: 0.02;
            precip_in: 0.0;
            humidity: 95;
            cloud: 100;
            feelslike_c: -10.4;
            feelslike_f: 13.3;
            windchill_c: -10.4;
            windchill_f: 13.3;
            heatindex_c: -4.8;
            heatindex_f: 23.3;
            dewpoint_c: -5.5;
            dewpoint_f: 22.1;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 79;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 14.2;
            gust_kph: 22.9;
            uv: 1.0;
          },
          {
            time_epoch: 1701720000;
            time: "2023-12-04 23:00";
            temp_c: -5.5;
            temp_f: 22.1;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 8.9;
            wind_kph: 14.4;
            wind_degree: 242;
            wind_dir: "WSW";
            pressure_mb: 1020.0;
            pressure_in: 30.13;
            precip_mm: 0.02;
            precip_in: 0.0;
            humidity: 95;
            cloud: 100;
            feelslike_c: -11.0;
            feelslike_f: 12.1;
            windchill_c: -11.0;
            windchill_f: 12.1;
            heatindex_c: -5.5;
            heatindex_f: 22.1;
            dewpoint_c: -6.2;
            dewpoint_f: 20.9;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 83;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 14.0;
            gust_kph: 22.5;
            uv: 1.0;
          },
        ];
      },
      {
        date: "2023-12-05";
        date_epoch: 1701734400;
        day: {
          maxtemp_c: -5.1;
          maxtemp_f: 22.8;
          mintemp_c: -13.6;
          mintemp_f: 7.5;
          avgtemp_c: -8.7;
          avgtemp_f: 16.4;
          maxwind_mph: 9.8;
          maxwind_kph: 15.8;
          totalprecip_mm: 0.31;
          totalprecip_in: 0.01;
          totalsnow_cm: 0.21;
          avgvis_km: 3.8;
          avgvis_miles: 2.0;
          avghumidity: 97.0;
          daily_will_it_rain: 0;
          daily_chance_of_rain: 67;
          daily_will_it_snow: 0;
          daily_chance_of_snow: 26;
          condition: {
            text: "Mist";
            icon: "//cdn.weatherapi.com/weather/64x64/day/143.png";
            code: 1030;
          };
          uv: 1.0;
        };
        astro: {
          sunrise: "09:10 AM";
          sunset: "04:50 PM";
          moonrise: "No moonrise";
          moonset: "02:12 PM";
          moon_phase: "Last Quarter";
          moon_illumination: 52;
          is_moon_up: 1;
          is_sun_up: 0;
        };
        hour: [
          {
            time_epoch: 1701723600;
            time: "2023-12-05 00:00";
            temp_c: -6.4;
            temp_f: 20.4;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 9.2;
            wind_kph: 14.8;
            wind_degree: 238;
            wind_dir: "WSW";
            pressure_mb: 1021.0;
            pressure_in: 30.14;
            precip_mm: 0.03;
            precip_in: 0.0;
            humidity: 95;
            cloud: 100;
            feelslike_c: -12.3;
            feelslike_f: 9.9;
            windchill_c: -12.3;
            windchill_f: 9.9;
            heatindex_c: -6.4;
            heatindex_f: 20.4;
            dewpoint_c: -7.1;
            dewpoint_f: 19.3;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 62;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 15.1;
            gust_kph: 24.4;
            uv: 1.0;
          },
          {
            time_epoch: 1701727200;
            time: "2023-12-05 01:00";
            temp_c: -6.8;
            temp_f: 19.8;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 8.9;
            wind_kph: 14.4;
            wind_degree: 238;
            wind_dir: "WSW";
            pressure_mb: 1021.0;
            pressure_in: 30.14;
            precip_mm: 0.05;
            precip_in: 0.0;
            humidity: 95;
            cloud: 100;
            feelslike_c: -12.6;
            feelslike_f: 9.3;
            windchill_c: -12.6;
            windchill_f: 9.3;
            heatindex_c: -6.8;
            heatindex_f: 19.9;
            dewpoint_c: -7.4;
            dewpoint_f: 18.7;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 69;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 14.7;
            gust_kph: 23.6;
            uv: 1.0;
          },
          {
            time_epoch: 1701730800;
            time: "2023-12-05 02:00";
            temp_c: -7.3;
            temp_f: 18.8;
            is_day: 0;
            condition: {
              text: "Light freezing rain";
              icon: "//cdn.weatherapi.com/weather/64x64/night/311.png";
              code: 1198;
            };
            wind_mph: 8.3;
            wind_kph: 13.3;
            wind_degree: 237;
            wind_dir: "WSW";
            pressure_mb: 1021.0;
            pressure_in: 30.14;
            precip_mm: 0.01;
            precip_in: 0.0;
            humidity: 96;
            cloud: 99;
            feelslike_c: -13.1;
            feelslike_f: 8.5;
            windchill_c: -13.1;
            windchill_f: 8.5;
            heatindex_c: -7.4;
            heatindex_f: 18.8;
            dewpoint_c: -7.9;
            dewpoint_f: 17.8;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 62;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 14.5;
            gust_kph: 23.3;
            uv: 1.0;
          },
          {
            time_epoch: 1701734400;
            time: "2023-12-05 03:00";
            temp_c: -8.5;
            temp_f: 16.7;
            is_day: 0;
            condition: {
              text: "Light freezing rain";
              icon: "//cdn.weatherapi.com/weather/64x64/night/311.png";
              code: 1198;
            };
            wind_mph: 8.1;
            wind_kph: 13.0;
            wind_degree: 233;
            wind_dir: "SW";
            pressure_mb: 1021.0;
            pressure_in: 30.14;
            precip_mm: 0.01;
            precip_in: 0.0;
            humidity: 97;
            cloud: 100;
            feelslike_c: -14.4;
            feelslike_f: 6.2;
            windchill_c: -14.4;
            windchill_f: 6.2;
            heatindex_c: -8.5;
            heatindex_f: 16.7;
            dewpoint_c: -8.9;
            dewpoint_f: 16.0;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 87;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 16.1;
            gust_kph: 26.0;
            uv: 1.0;
          },
          {
            time_epoch: 1701738000;
            time: "2023-12-05 04:00";
            temp_c: -7.4;
            temp_f: 18.7;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 9.2;
            wind_kph: 14.8;
            wind_degree: 238;
            wind_dir: "WSW";
            pressure_mb: 1021.0;
            pressure_in: 30.15;
            precip_mm: 0.02;
            precip_in: 0.0;
            humidity: 96;
            cloud: 100;
            feelslike_c: -13.5;
            feelslike_f: 7.7;
            windchill_c: -13.5;
            windchill_f: 7.7;
            heatindex_c: -7.4;
            heatindex_f: 18.7;
            dewpoint_c: -8.0;
            dewpoint_f: 17.7;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 79;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 16.8;
            gust_kph: 27.0;
            uv: 1.0;
          },
          {
            time_epoch: 1701741600;
            time: "2023-12-05 05:00";
            temp_c: -5.9;
            temp_f: 21.4;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 9.8;
            wind_kph: 15.8;
            wind_degree: 240;
            wind_dir: "WSW";
            pressure_mb: 1021.0;
            pressure_in: 30.16;
            precip_mm: 0.05;
            precip_in: 0.0;
            humidity: 95;
            cloud: 98;
            feelslike_c: -11.9;
            feelslike_f: 10.7;
            windchill_c: -11.9;
            windchill_f: 10.7;
            heatindex_c: -5.9;
            heatindex_f: 21.4;
            dewpoint_c: -6.6;
            dewpoint_f: 20.1;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 1;
            chance_of_snow: 71;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 15.9;
            gust_kph: 25.6;
            uv: 1.0;
          },
          {
            time_epoch: 1701745200;
            time: "2023-12-05 06:00";
            temp_c: -5.4;
            temp_f: 22.4;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 9.8;
            wind_kph: 15.8;
            wind_degree: 241;
            wind_dir: "WSW";
            pressure_mb: 1022.0;
            pressure_in: 30.17;
            precip_mm: 0.05;
            precip_in: 0.0;
            humidity: 95;
            cloud: 93;
            feelslike_c: -11.2;
            feelslike_f: 11.8;
            windchill_c: -11.2;
            windchill_f: 11.8;
            heatindex_c: -5.4;
            heatindex_f: 22.4;
            dewpoint_c: -6.1;
            dewpoint_f: 21.1;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 70;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 15.3;
            gust_kph: 24.7;
            uv: 1.0;
          },
          {
            time_epoch: 1701748800;
            time: "2023-12-05 07:00";
            temp_c: -5.4;
            temp_f: 22.2;
            is_day: 0;
            condition: {
              text: "Light snow";
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png";
              code: 1213;
            };
            wind_mph: 8.9;
            wind_kph: 14.4;
            wind_degree: 239;
            wind_dir: "WSW";
            pressure_mb: 1022.0;
            pressure_in: 30.18;
            precip_mm: 0.03;
            precip_in: 0.0;
            humidity: 95;
            cloud: 91;
            feelslike_c: -11.0;
            feelslike_f: 12.2;
            windchill_c: -11.0;
            windchill_f: 12.2;
            heatindex_c: -5.5;
            heatindex_f: 22.2;
            dewpoint_c: -6.2;
            dewpoint_f: 20.9;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 66;
            vis_km: 10.0;
            vis_miles: 6.0;
            gust_mph: 14.4;
            gust_kph: 23.2;
            uv: 1.0;
          },
          {
            time_epoch: 1701752400;
            time: "2023-12-05 08:00";
            temp_c: -6.3;
            temp_f: 20.7;
            is_day: 0;
            condition: {
              text: "Mist";
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png";
              code: 1030;
            };
            wind_mph: 7.4;
            wind_kph: 11.9;
            wind_degree: 236;
            wind_dir: "WSW";
            pressure_mb: 1022.0;
            pressure_in: 30.19;
            precip_mm: 0.01;
            precip_in: 0.0;
            humidity: 95;
            cloud: 83;
            feelslike_c: -11.4;
            feelslike_f: 11.6;
            windchill_c: -11.4;
            windchill_f: 11.6;
            heatindex_c: -6.3;
            heatindex_f: 20.8;
            dewpoint_c: -6.9;
            dewpoint_f: 19.6;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 65;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 13.6;
            gust_kph: 21.8;
            uv: 1.0;
          },
          {
            time_epoch: 1701756000;
            time: "2023-12-05 09:00";
            temp_c: -7.4;
            temp_f: 18.6;
            is_day: 0;
            condition: {
              text: "Mist";
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png";
              code: 1030;
            };
            wind_mph: 6.0;
            wind_kph: 9.7;
            wind_degree: 228;
            wind_dir: "SW";
            pressure_mb: 1023.0;
            pressure_in: 30.21;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 97;
            cloud: 84;
            feelslike_c: -12.1;
            feelslike_f: 10.2;
            windchill_c: -12.1;
            windchill_f: 10.2;
            heatindex_c: -7.4;
            heatindex_f: 18.6;
            dewpoint_c: -7.9;
            dewpoint_f: 17.8;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 12.7;
            gust_kph: 20.4;
            uv: 1.0;
          },
          {
            time_epoch: 1701759600;
            time: "2023-12-05 10:00";
            temp_c: -7.6;
            temp_f: 18.3;
            is_day: 1;
            condition: {
              text: "Freezing fog";
              icon: "//cdn.weatherapi.com/weather/64x64/day/260.png";
              code: 1147;
            };
            wind_mph: 4.9;
            wind_kph: 7.9;
            wind_degree: 226;
            wind_dir: "SW";
            pressure_mb: 1023.0;
            pressure_in: 30.22;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 97;
            cloud: 77;
            feelslike_c: -11.6;
            feelslike_f: 11.1;
            windchill_c: -11.6;
            windchill_f: 11.1;
            heatindex_c: -7.6;
            heatindex_f: 18.3;
            dewpoint_c: -8.0;
            dewpoint_f: 17.7;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 0.0;
            vis_miles: 0.0;
            gust_mph: 10.3;
            gust_kph: 16.6;
            uv: 1.0;
          },
          {
            time_epoch: 1701763200;
            time: "2023-12-05 11:00";
            temp_c: -6.4;
            temp_f: 20.5;
            is_day: 1;
            condition: {
              text: "Mist";
              icon: "//cdn.weatherapi.com/weather/64x64/day/143.png";
              code: 1030;
            };
            wind_mph: 4.3;
            wind_kph: 6.8;
            wind_degree: 226;
            wind_dir: "SW";
            pressure_mb: 1024.0;
            pressure_in: 30.23;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 96;
            cloud: 65;
            feelslike_c: -9.8;
            feelslike_f: 14.4;
            windchill_c: -9.8;
            windchill_f: 14.4;
            heatindex_c: -6.4;
            heatindex_f: 20.5;
            dewpoint_c: -6.9;
            dewpoint_f: 19.6;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 8.3;
            gust_kph: 13.3;
            uv: 1.0;
          },
          {
            time_epoch: 1701766800;
            time: "2023-12-05 12:00";
            temp_c: -5.3;
            temp_f: 22.4;
            is_day: 1;
            condition: {
              text: "Mist";
              icon: "//cdn.weatherapi.com/weather/64x64/day/143.png";
              code: 1030;
            };
            wind_mph: 4.5;
            wind_kph: 7.2;
            wind_degree: 219;
            wind_dir: "SW";
            pressure_mb: 1024.0;
            pressure_in: 30.22;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 95;
            cloud: 73;
            feelslike_c: -8.7;
            feelslike_f: 16.4;
            windchill_c: -8.7;
            windchill_f: 16.4;
            heatindex_c: -5.3;
            heatindex_f: 22.4;
            dewpoint_c: -6.0;
            dewpoint_f: 21.2;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 7.7;
            gust_kph: 12.5;
            uv: 1.0;
          },
          {
            time_epoch: 1701770400;
            time: "2023-12-05 13:00";
            temp_c: -5.1;
            temp_f: 22.8;
            is_day: 1;
            condition: {
              text: "Mist";
              icon: "//cdn.weatherapi.com/weather/64x64/day/143.png";
              code: 1030;
            };
            wind_mph: 4.9;
            wind_kph: 7.9;
            wind_degree: 205;
            wind_dir: "SSW";
            pressure_mb: 1024.0;
            pressure_in: 30.23;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 95;
            cloud: 83;
            feelslike_c: -8.7;
            feelslike_f: 16.3;
            windchill_c: -8.7;
            windchill_f: 16.3;
            heatindex_c: -5.1;
            heatindex_f: 22.8;
            dewpoint_c: -5.8;
            dewpoint_f: 21.5;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 8.3;
            gust_kph: 13.4;
            uv: 1.0;
          },
          {
            time_epoch: 1701774000;
            time: "2023-12-05 14:00";
            temp_c: -5.9;
            temp_f: 21.3;
            is_day: 1;
            condition: {
              text: "Mist";
              icon: "//cdn.weatherapi.com/weather/64x64/day/143.png";
              code: 1030;
            };
            wind_mph: 4.7;
            wind_kph: 7.6;
            wind_degree: 199;
            wind_dir: "SSW";
            pressure_mb: 1024.0;
            pressure_in: 30.23;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 96;
            cloud: 70;
            feelslike_c: -9.5;
            feelslike_f: 14.8;
            windchill_c: -9.5;
            windchill_f: 14.8;
            heatindex_c: -5.9;
            heatindex_f: 21.3;
            dewpoint_c: -6.5;
            dewpoint_f: 20.3;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 2.0;
            vis_miles: 1.0;
            gust_mph: 8.7;
            gust_kph: 14.0;
            uv: 1.0;
          },
          {
            time_epoch: 1701777600;
            time: "2023-12-05 15:00";
            temp_c: -8.4;
            temp_f: 16.8;
            is_day: 1;
            condition: {
              text: "Freezing fog";
              icon: "//cdn.weatherapi.com/weather/64x64/day/260.png";
              code: 1147;
            };
            wind_mph: 3.8;
            wind_kph: 6.1;
            wind_degree: 182;
            wind_dir: "S";
            pressure_mb: 1024.0;
            pressure_in: 30.24;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 98;
            cloud: 49;
            feelslike_c: -11.8;
            feelslike_f: 10.8;
            windchill_c: -11.8;
            windchill_f: 10.8;
            heatindex_c: -8.4;
            heatindex_f: 16.8;
            dewpoint_c: -8.7;
            dewpoint_f: 16.3;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 0.0;
            vis_miles: 0.0;
            gust_mph: 8.0;
            gust_kph: 12.9;
            uv: 1.0;
          },
          {
            time_epoch: 1701781200;
            time: "2023-12-05 16:00";
            temp_c: -11.1;
            temp_f: 12.0;
            is_day: 1;
            condition: {
              text: "Freezing fog";
              icon: "//cdn.weatherapi.com/weather/64x64/day/260.png";
              code: 1147;
            };
            wind_mph: 3.8;
            wind_kph: 6.1;
            wind_degree: 172;
            wind_dir: "S";
            pressure_mb: 1025.0;
            pressure_in: 30.26;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 99;
            cloud: 42;
            feelslike_c: -14.9;
            feelslike_f: 5.2;
            windchill_c: -14.9;
            windchill_f: 5.2;
            heatindex_c: -11.1;
            heatindex_f: 12.0;
            dewpoint_c: -11.3;
            dewpoint_f: 11.7;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 0.0;
            vis_miles: 0.0;
            gust_mph: 8.0;
            gust_kph: 12.9;
            uv: 1.0;
          },
          {
            time_epoch: 1701784800;
            time: "2023-12-05 17:00";
            temp_c: -12.5;
            temp_f: 9.5;
            is_day: 0;
            condition: {
              text: "Freezing fog";
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png";
              code: 1147;
            };
            wind_mph: 3.8;
            wind_kph: 6.1;
            wind_degree: 153;
            wind_dir: "SSE";
            pressure_mb: 1025.0;
            pressure_in: 30.27;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 99;
            cloud: 40;
            feelslike_c: -16.5;
            feelslike_f: 2.4;
            windchill_c: -16.5;
            windchill_f: 2.4;
            heatindex_c: -12.5;
            heatindex_f: 9.5;
            dewpoint_c: -12.6;
            dewpoint_f: 9.4;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 0.0;
            vis_miles: 0.0;
            gust_mph: 8.0;
            gust_kph: 12.9;
            uv: 1.0;
          },
          {
            time_epoch: 1701788400;
            time: "2023-12-05 18:00";
            temp_c: -13.2;
            temp_f: 8.2;
            is_day: 0;
            condition: {
              text: "Freezing fog";
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png";
              code: 1147;
            };
            wind_mph: 4.0;
            wind_kph: 6.5;
            wind_degree: 136;
            wind_dir: "SE";
            pressure_mb: 1025.0;
            pressure_in: 30.27;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 100;
            cloud: 47;
            feelslike_c: -17.5;
            feelslike_f: 0.5;
            windchill_c: -17.5;
            windchill_f: 0.5;
            heatindex_c: -13.2;
            heatindex_f: 8.2;
            dewpoint_c: -13.3;
            dewpoint_f: 8.2;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 0.0;
            vis_miles: 0.0;
            gust_mph: 8.5;
            gust_kph: 13.6;
            uv: 1.0;
          },
          {
            time_epoch: 1701792000;
            time: "2023-12-05 19:00";
            temp_c: -13.6;
            temp_f: 7.5;
            is_day: 0;
            condition: {
              text: "Freezing fog";
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png";
              code: 1147;
            };
            wind_mph: 4.0;
            wind_kph: 6.5;
            wind_degree: 130;
            wind_dir: "SE";
            pressure_mb: 1025.0;
            pressure_in: 30.28;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 100;
            cloud: 56;
            feelslike_c: -18.0;
            feelslike_f: -0.4;
            windchill_c: -18.0;
            windchill_f: -0.4;
            heatindex_c: -13.6;
            heatindex_f: 7.5;
            dewpoint_c: -13.7;
            dewpoint_f: 7.4;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 0.0;
            vis_miles: 0.0;
            gust_mph: 8.5;
            gust_kph: 13.6;
            uv: 1.0;
          },
          {
            time_epoch: 1701795600;
            time: "2023-12-05 20:00";
            temp_c: -13.3;
            temp_f: 8.1;
            is_day: 0;
            condition: {
              text: "Freezing fog";
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png";
              code: 1147;
            };
            wind_mph: 4.9;
            wind_kph: 7.9;
            wind_degree: 124;
            wind_dir: "SE";
            pressure_mb: 1026.0;
            pressure_in: 30.29;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 100;
            cloud: 51;
            feelslike_c: -18.3;
            feelslike_f: -0.9;
            windchill_c: -18.3;
            windchill_f: -0.9;
            heatindex_c: -13.3;
            heatindex_f: 8.1;
            dewpoint_c: -13.3;
            dewpoint_f: 8.1;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 0.0;
            vis_miles: 0.0;
            gust_mph: 10.3;
            gust_kph: 16.6;
            uv: 1.0;
          },
          {
            time_epoch: 1701799200;
            time: "2023-12-05 21:00";
            temp_c: -12.9;
            temp_f: 8.7;
            is_day: 0;
            condition: {
              text: "Freezing fog";
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png";
              code: 1147;
            };
            wind_mph: 5.4;
            wind_kph: 8.6;
            wind_degree: 120;
            wind_dir: "ESE";
            pressure_mb: 1026.0;
            pressure_in: 30.29;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 99;
            cloud: 41;
            feelslike_c: -18.2;
            feelslike_f: -0.8;
            windchill_c: -18.2;
            windchill_f: -0.8;
            heatindex_c: -12.9;
            heatindex_f: 8.7;
            dewpoint_c: -13.0;
            dewpoint_f: 8.6;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 0.0;
            vis_miles: 0.0;
            gust_mph: 11.3;
            gust_kph: 18.1;
            uv: 1.0;
          },
          {
            time_epoch: 1701802800;
            time: "2023-12-05 22:00";
            temp_c: -12.8;
            temp_f: 8.9;
            is_day: 0;
            condition: {
              text: "Freezing fog";
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png";
              code: 1147;
            };
            wind_mph: 5.8;
            wind_kph: 9.4;
            wind_degree: 117;
            wind_dir: "ESE";
            pressure_mb: 1026.0;
            pressure_in: 30.29;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 99;
            cloud: 34;
            feelslike_c: -18.4;
            feelslike_f: -1.1;
            windchill_c: -18.4;
            windchill_f: -1.1;
            heatindex_c: -12.8;
            heatindex_f: 8.9;
            dewpoint_c: -13.0;
            dewpoint_f: 8.7;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 0.0;
            vis_miles: 0.0;
            gust_mph: 12.2;
            gust_kph: 19.7;
            uv: 1.0;
          },
          {
            time_epoch: 1701806400;
            time: "2023-12-05 23:00";
            temp_c: -12.8;
            temp_f: 8.9;
            is_day: 0;
            condition: {
              text: "Freezing fog";
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png";
              code: 1147;
            };
            wind_mph: 6.0;
            wind_kph: 9.7;
            wind_degree: 111;
            wind_dir: "ESE";
            pressure_mb: 1026.0;
            pressure_in: 30.29;
            precip_mm: 0.0;
            precip_in: 0.0;
            humidity: 98;
            cloud: 21;
            feelslike_c: -18.6;
            feelslike_f: -1.4;
            windchill_c: -18.6;
            windchill_f: -1.4;
            heatindex_c: -12.9;
            heatindex_f: 8.9;
            dewpoint_c: -13.1;
            dewpoint_f: 8.4;
            will_it_rain: 0;
            chance_of_rain: 0;
            will_it_snow: 0;
            chance_of_snow: 0;
            vis_km: 0.0;
            vis_miles: 0.0;
            gust_mph: 12.7;
            gust_kph: 20.4;
            uv: 1.0;
          },
        ];
      },
    ];
  };
}
